
let _ = 2 + 7 in 
let _ = print ("he" + "llo") in 
let _ = print (42) in
let _ = print "yay" in
let x = 4 in
let y = 7 in
let x = 2 in
let _ = print (x + y) in
let _ = print (3) in
let _ = print (if (2 <> 4) then (3 < 4) else 4) in
let _ = print 2 = 2 in
let _ = print 2 <= 2 in
let _ = print 3 >= 2 in
let _ = print 3 >= 3 in
let _ = print 4 > 2 in
let _ = print 4 > 5 in
let _ = 1 | 0 in
let _ = 1 & 1 in 0
