let _ = print (100 & 200) in
let _ = print (100 & 0) in
let _ = print (100 | 200) in
let _ = print (100 | 0) in
let _ = print (1234 + 4321) in
let _ = print (1234 - 4321) in
let _ = print (1234 * 4321) in
let _ = print (1234 / 4321) in
let _ = print (4321 / 1234) in
let _ = print (1234 > 4321) in
let _ = print (4321 > 1234) in
let _ = print (1234 > 1234) in
let _ = print (1234 < 4321) in
let _ = print (4321 < 1234) in
let _ = print (1234 < 1234) in
let _ = print (1234 >= 4321) in
let _ = print (4321 >= 1234) in
let _ = print (1234 >= 1234) in
let _ = print (1234 <= 4321) in
let _ = print (4321 <= 1234) in
let _ = print (1234 <= 1234) in
let _ = print (0 | 0) in
let _ = print ("abc" = "abc") in
let _ = print ("a" + "b" + "c" = "abc") in
let _ = print ("abc" = "xyz") in
let _ = print ("a" = "") in
let _ = print ("a" = "" + "a") in
let _ = print ("" = "") in
let _ = print ("abc" <> "abc") in
let _ = print ("abc" <> "xyz") in
let _ = print ("" <> "") in
17
